services:
  approval-notary:
    image: ${image_repository}@sha256:${image_sha256}

    environment:
      HMZ_NOTARY_COLS_DIR: "/data/anti-rewind"
      HMZ_HC_TRACING_ENABLED: "true"
      HMZ_HC_TRACING_ENABLED: "true"
      HMZ_OPEN_TELEMETRY_TYPE: "disabled"
      HMZ_NOTARY_BRIDGE_HTTP_URI: ${harmonize_notary_bridge_endpoint}
      HMZ_NOTARY_BRIDGE_HTTP_ENABLED: "true"
      HMZ_LOG_LEVEL: "TRACE"
      HMZ_NOTARY_BRIDGE_GRPC_ENABLED: "false"
      HMZ_NOTARY_HPCS_ENABLED: "true"
      HMZ_NOTARY_HPCS_HOST: ${crypto_server_ep11_host}
      HMZ_NOTARY_HPCS_GRPC_PORT: ${crypto_server_ep11_port}

      # IBM LinuxONE on-premise
      HMZ_NOTARY_HPCS_CLIENT_CERT_ENABLED: "true"
      HMZ_NOTARY_HPCS_CERT_CA_FILE: "/opt/approval-notary/cert/ca.pem"
      HMZ_NOTARY_HPCS_CERT_CHAIN_FILE: "/opt/approval-notary/cert/client-certificate-chain.pem"
      HMZ_NOTARY_HPCS_CERT_KEY_FILE: "/opt/approval-notary/cert/client-key.pkcs8.pem"

    entrypoint: [ "/bin/bash", "-c" ]
    command:
      - | 
        # add "echo  "<Ip addr of LPAR hosting grep11 server">:<domain used in setting grep11>" >> /etc/hosts
        /opt/entrypoint.sh

    volumes:
      # This is a must as it is needed for anti-rewind file
      - "/mnt/data:/data"

      # This is only for communicating with grep11 server
      - ".cert:/opt/approval-notary/cert:ro"
