services:
  vault-releases:
    image: ${image_repository}@sha256:${image_sha256}
    environment:
      PLATFORM: "ibm"
      VAULT_ID: ${vault_id}
      HARMONIZE_CORE_ENDPOINT: ${harmonize_api_endpoint}/internal/v1
      VAULT_IBM_SYSTEM: "cloud"
      VAULT_IBM_CRYPTO_SERVER_ENDPOINT: ${crypto_server_ep11_endpoint}
      VAULT_IBM_CRYPTO_SERVER_API_KEY: ${crypto_server_access_api_key}
      VAULT_IBM_CRYPTO_SERVER_INSTANCE_ID: ${crypto_server_instance_id}
      VAULT_TRUSTED_SIG: pem:${notary_messaging_public_key}
      HMZ_LOG_LEVEL: "TRACE"
